Update: add command to build app for all os and architecture in Makefile

diff --git a/auth-service/Makefile b/auth-service/Makefile
--- a/auth-service/Makefile
+++ b/auth-service/Makefile
@@ -1,3 +1,8 @@
+# Variables
+OUTPUT		:= app
+BIN_DIR     := ./bin
+PLATFORMS   := linux/amd64 linux/386 linux/arm linux/arm64 windows/amd64 windows/386 darwin/amd64 darwin/arm64
+
 help: ## Show this help message
 	@printf "\033[36m%-30s\033[0m %s\n" "Target" "Description"
 	@printf "\033[36m%-30s\033[0m %s\n" "------" "-----------"
@@ -7,7 +12,7 @@ all: build run ## Execute all steps `clean update check swagger build run`
 
 clean: ## Clean build artifacts
 	@echo "Cleaning..."
-	@rm -rf ./bin/
+	@rm -rf $(BIN_DIR)/
 	@rm -rf ./logs/
 	@rm -f coverage.out coverage.html
 	@echo "Clean complete"
@@ -50,12 +55,29 @@ build: clean check swagger ## Build the application
 	@echo "Building application..."
 	@go mod tidy
 	@go generate ./src/cmd
-	@go build -o ./bin/app ./src/cmd
+	@go build -o $(BIN_DIR)/$(OUTPUT) ./src/cmd
 	@echo "Build complete: bin/app"
+
+build-all: ## Cross-compile for all operating system (e.g., linux, windows, darwin, freebsd) & architecture (e.g., amd64, 386, arm, arm64)
+	@for platform in $(PLATFORMS); do \
+		GOOS=$${platform%/*}; \
+		GOARCH=$${platform#*/}; \
+		output_name=$(OUTPUT)-$$GOOS-$$GOARCH; \
+		if [ "$$GOOS" = "windows" ]; then \
+			output_name="$$output_name.exe"; \
+		fi; \
+		echo "Building for $$GOOS/$$GOARCH..."; \
+		env GOOS=$$GOOS GOARCH=$$GOARCH go build -o $(BIN_DIR)/$$output_name ./src/cmd; \
+		if [ $$? -ne 0 ]; then \
+			echo "Error building for $$GOOS/$$GOARCH"; \
+			exit 1; \
+		fi; \
+	done
+	@echo "All builds completed successfully. Binaries are in $(BIN_DIR)/"
 
 run: ## Run the application
 	@echo "Starting application..."
-	@./bin/app
+	@$(BIN_DIR)/$(OUTPUT)
 
 deps: ## Install dependencies
 	@echo "Installing dependencies..."
